# TheHiddenMC Configuration

settings:
    use-TagAPI: false
    protect-signs: true
messages:
    prefix: '&d[Hidden] &8|| '
    sign-error: '&cCould not create a TheHiddenMC sign!'
    sign-create: '&aTheHidden sign succesfully created!'
    sign-destroy: '&aTheHidden sign successfully destroyed!'
    sign-join: '&aThis is a TheHiddenMC sign!'
    no-permission: '&cYou do not have permission to do that!'
signs:
    hidden-sign-text: '[HIDDEN]'
