# TheHiddenMC Configuration
settings:
  use-TagAPI: false
  protect-signs: true
  enabled-world: 'world'
signs:
  hidden-sign-text: '[HIDDEN]'
messages:
  prefix: '&d[Hidden] &8|| '
  sign-error: '&cCould not create a TheHiddenMC sign!'
  sign-create: '&aTheHidden sign succesfully created!'
  sign-destroy: '&aTheHidden sign successfully destroyed!'
  sign-join: '&aThis is a TheHiddenMC sign!'
  no-permission: '&cYou do not have permission to do that!'
  not-hidden-world: '&cThis world is not a Hidden world!'
  commands:
    reload: '&aConfig reloaded!'